apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: devops
  labels:
    app: nginx
    author: zbw
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
